### ISSUE TITLE
Vhost Request

### ISSUE THREAD

**Issue by TwinUsers** [XthemeOrg/SWI#1]
When requesting a vhost within SWI interface i get nick ? not registered

I've followed the install guide, every else works fine

**Comment by siniStar7boy** [comment]
Not able to reproduce this issue.

Is the nickname indeed registered and verified?  What vhost is attempting to be requested?

**Comment by TwinUsers** [comment]
Nick is indeed registered and verified, a simple vhost like test.com throws the error.

Not sure if it's because am using a old forked version?

**Comment by siniStar7boy** [comment]
It probably is.  Git clone from XthemeOrg or download the zip from the XthemeOrg/SWI releases tab.
