### ISSUE TITLE
SWI Dont work with PHP 7

### ISSUE THREAD

**Issue by Taxick** [XthemeOrg/SWI#3]
Hi.

Last version of SWI don't work with PHP 7 - Hope it can be fixed.

I get this errors when I'm try to load the page.

** A PHP Error was encountered
Severity: Notice

Message: Only variables should be assigned by reference

Filename: core/Loader.php

Line Number: 46 **

**Comment by siniStar7boy** [comment]
I will look into this - I am pretty sure someone reported a similar issue with PHP 7.

**Comment by fgrosswig** [comment]
i have changed line 46 as follow:

` // $this->_base_classes =& is_loaded();
   $this->_base_classes = is_loaded();` 

this solved the error but it popped up new errors reported here: #6 

still not useable to php7 😢
