### ISSUE TITLE
SWI PHP error?

### ISSUE THREAD

**Issue by Agent-Isai** [XthemeOrg/SWI#8]
Hello, for some reason when I go to http://panel.mydomain.com/SWI I encounter this error:

<b>A PHP Error was encountered</b>

Severity: Notice

Message: Only variable references should be returned by reference

Filename: core/Common.php

Line Number: 157

**Comment by siniStar7boy** [comment]
Can you provide more information such as your OS & version, PHP version and if possible a paste of your webserver's error_log?

**Comment by Agent-Isai** [comment]
Hi, I'm using Debian version Jessie (8), I'm using PHP 5.6.7-1 and I got this from my error.log on my server

[Mon May 04 18:18:00.008564 2015] [:error] [pid 20173] [client <IP>:65285] PHP Parse error:  syntax error, unexpected end of file in /var/www/site/subdomain/SWI/swi/views/response.php on line 27

**Comment by siniStar7boy** [comment]
@Agent-Isai Can you please email your SWI config file to siniStar @ IRC4Fun.net and provide the URL of your installation of SWI, please?  _Also, the version of your Xtheme/Atheme/Atheme fork instance would also be helpful._

**Comment by siniStar7boy** [comment]
Closing this issue as requested information was not provided.

**Comment by adamus1red** [comment]
@siniStar7boy I'm currently having the same issue do you want me to email you my config?

**Comment by siniStar7boy** [comment]
Yes, please - siniStar[at]IRC4Fun.net

**Comment by adamus1red** [comment]
Sent

**Comment by siniStar7boy** [comment]
**Thanks @adamus1red for fixing this issue.**  @Agent-Isai _(If you are still using Xtheme or an Atheme fork, this should fix SWI for you as well)_  

_Thank you both for your contributions towards making SWI better for everyone!_
