### ISSUE TITLE
Dashboard -> Current Logins: PHP Error

### ISSUE THREAD

**Issue by AlphaT3ch** [XthemeOrg/SWI#9]
A PHP Error was encountered
Severity: Warning
Message: Invalid argument supplied for foreach()
Filename: views/logins.php
Line Number: 12

**Comment by siniStar7boy** [comment]
@AlphaT3ch Did you enable 'contrib/ns_listlogins' in Xtheme (or atheme) and REHASH Xtheme (or atheme)?  

This is a result of the required (contrib/ns_listlogins) module not being loaded in Xtheme or Atheme.  Please let me know if this resolved your issue either via IRC or by replying to this issue.

**Comment by siniStar7boy** [comment]
Closing this issue as it can only be replicated _(so far)_ by not having ``contrib/ns_listlogins`` module not loaded in Xtheme, Atheme, or Atheme fork.  Therefor it is not really an issue.  **It is noted quite clearly in the configuration file that the module must be loaded in the IRC Services instance before enabling in SWI.**

**Comment by AlphaT3ch** [comment]
Ah thanks @siniStar7boy, I had ns_listchans, ns_listgroups and ns_listmail enabled. I cannot seem to find nc_listlogins though.
